# Generated by Django 2.2 on 2019-05-16 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BooksCollection', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
