# Generated by Django 2.2 on 2019-05-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksCollection', '0002_auto_20190516_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_categories',
            field=models.ManyToManyField(null=True, to='BooksCollection.Category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_description',
            field=models.TextField(null=True),
        ),
    ]
